### PR TITLE
Add service for dumping study table to csv (issue 33)

### PR DESCRIPTION
**Pull request by pmidford**
Implement service to dump contents of the study table to csv (.../phylografter/study/export_csv.csv).

### CODE REVIEW

**Comment by rhr** [comment]
Merged and deployed - thanks Peter!

**Comment by jar398** [comment]
Yes, thanks to both of you. Jonathan

**Comment by jimallman** [comment]
@jar398: Does the dumped info above have any bearing on the bibliographic-references page for the synthetic view? 

I assume the info in phylografter is moot, since treemachine knows all the studies that contributed to the current synthetic tree. I just want to be sure we don't need separate references for these studies.

**Comment by jar398** [comment]
The old study table dump service is fragile since the columns change every
time the SQL table in phylografter changes. And there are no column
headings as I remember. My application was the DOI harvesting setup, which
I haven't tried to run in a while (there are bugs in the crossref service I
was using that were hard to track down or circumvent).

The references metadata is of course in the studies themselves (in nexson
form or in tables in phylografter), and gets copied from there to oti and
treemachine. I thought you'd be able to use the oti service that the
curator uses, maybe caching the result (since the set of studies in
treemachine doesn't change very often). To get the information from
treemachine would require creating a new service.

**Comment by jimallman** [comment]
> I thought you'd be able to use the oti service that the curator uses, maybe caching the result (since the set of studies in treemachine doesn't change very often). 

Agreed, this already includes the full reference text and DOI.

**Pull request merged**
