### PR TITLE
fix doi processing and correctly generate citation string literals (not hrefs)

### PR DESCRIPTION
**Pull request by pmidford**

### CODE REVIEW

**Comment by pmidford** [comment]
Except that bibliographicCitation is defined at DublinCore to have a literal as its range, rather than a resource.  I could just let these fall through as identifier links - ter:identifier (aka dc:identifier) is defined to have resource as its range), even though they're not doi's.

**Comment by jar398** [comment]
_None_ of the DC terms works for us here, so I suggest we create our own
property. In fact I'm doubtful about reuse of _any_ existing metadata
property names.

**Comment by pmidford** [comment]
That's Ok with me, but I think we need to discuss what we need to be covered in this vocabulary, assigning URI's and making these terms available outside the project etc. at the call tomorrow.

**Comment by jar398** [comment]
On Tue, Mar 5, 2013 at 3:51 PM, Peter Midford notifications@github.comwrote:

> That's Ok with me, but I think we need to discuss what we need to be
> covered in this vocabulary, assigning URI's and making these terms
> available outside the project etc. at the call tomorrow.
> 
> Maybe, but I think you and I are likely to be the only ones who care. AFAIK
> nobody else has any experience with RDF (which is what NeXML metadata seems
> to reduce to). We can mention tomorrow that this is something to be done,
> but I think it will turn into us preparing a plan, for presentation to
> others.

The first step would be to make a list of all the meanings that need to be
expressed. You're close to the phylografter code now so maybe you can do
this?

I think the situation with NeXML metadata is very screwy. I looked at a
treebase file and it doesn't make any sense at all, exhibiting very typical
RDF dysfunction. I think we can do better.

**Comment by pmidford** [comment]
Merging this request - development continues on NexSONMetaData branch

**Pull request merged**
